services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: serviceflow-sqlserver
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "ServiceFlow@2026!"
    ports:
      - "14330:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql

volumes:
  sqlserver_data: